package gitlab

// PipelineTrigger represents a CI/CD pipeline trigger token.
type PipelineTrigger struct {
	ID          int    `json:"id"`
	Description string `json:"description"`
	CreatedAt   string `json:"created_at"`
	LastUsed    string `json:"last_used"`
	Owner       *struct {
		Name     string `json:"name"`
		Username string `json:"username"`
	} `json:"owner"`
}

// PipelineTriggerRequest is the write body for POST.
// Token is auto-generated by GitLab — it cannot be copied from source.
type PipelineTriggerRequest struct {
	Description string `json:"description"`
}

// --- Read ---

func (c *Client) GetProjectTriggers(projectPath string) ([]PipelineTrigger, error) {
	var triggers []PipelineTrigger
	err := c.get("/projects/"+encodePath(projectPath)+"/triggers", nil, &triggers)
	if err != nil {
		if apiErr, ok := err.(*APIError); ok && (apiErr.IsNotFound() || apiErr.IsForbidden()) {
			return nil, nil
		}
		return nil, err
	}
	return triggers, nil
}

// PipelineTriggerResponse is the response from POST /triggers — includes
// the full token value which is only available at creation time.
type PipelineTriggerResponse struct {
	ID          int    `json:"id"`
	Description string `json:"description"`
	Token       string `json:"token"`
}

// --- Write ---

// CreateProjectTrigger creates a pipeline trigger on the dest project and
// returns the full response including the newly generated token value.
// The token is only available in this response — it cannot be retrieved later.
func (c *Client) CreateProjectTrigger(projectPath string, req PipelineTriggerRequest) (*PipelineTriggerResponse, error) {
	var resp PipelineTriggerResponse
	if err := c.post("/projects/"+encodePath(projectPath)+"/triggers", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
