package gitlab

// PipelineTrigger represents a CI/CD pipeline trigger token.
type PipelineTrigger struct {
	ID          int    `json:"id"`
	Description string `json:"description"`
	CreatedAt   string `json:"created_at"`
	LastUsed    string `json:"last_used"`
	Owner       *struct {
		Name     string `json:"name"`
		Username string `json:"username"`
	} `json:"owner"`
}

// PipelineTriggerRequest is the write body for POST.
// Token is auto-generated by GitLab — it cannot be copied from source.
type PipelineTriggerRequest struct {
	Description string `json:"description"`
}

// --- Read ---

func (c *Client) GetProjectTriggers(projectPath string) ([]PipelineTrigger, error) {
	var triggers []PipelineTrigger
	err := c.get("/projects/"+encodePath(projectPath)+"/triggers", nil, &triggers)
	if err != nil {
		if apiErr, ok := err.(*APIError); ok && (apiErr.IsNotFound() || apiErr.IsForbidden()) {
			return nil, nil
		}
		return nil, err
	}
	return triggers, nil
}

// --- Write ---

// CreateProjectTrigger creates a pipeline trigger on the dest project.
// Note: the trigger token is auto-generated and will differ from source.
func (c *Client) CreateProjectTrigger(projectPath string, req PipelineTriggerRequest) error {
	return c.post("/projects/"+encodePath(projectPath)+"/triggers", req, nil)
}
